### ISSUE TITLE
Add hooks

### ISSUE THREAD

**Issue by gopar** [bkaestner/secret-mode.el#6]
Handy package you got here :)

Wondering if you can add hooks to the mode?
Want to apply read-only so I do'nt accidentally type

**Comment by bkaestner** [comment]
Hey, thanks! There's already a hook called `redacted-mode-hook`, so you can add
```lisp
(add-hook 'redacted-mode-hook (lambda () (read-only-mode (if redacted-mode 1 -1))))
```
Does this fit your use-case?

**Comment by gopar** [comment]
oh snaps! forgot that minor modes automatically add hooks. I was just looking at the code itself. 

Thanks!

**Comment by bkaestner** [comment]
No worries, that's more or less a documentation issue. I've added your use case to the README, it might be a common one after all :).
